# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches: [production_v1]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Load Environment Variables
        run: |
          if [ "$GITHUB_EVENT_NAME" == "push" ] && [ "$GITHUB_REF" == "refs/heads/production_v1" ]; then
            echo "Loading production environment variables..."
            cp .env
          else
            echo "Loading default environment variables..."
            cp .env.development .env
          fi

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      # ( Build to ./dist or other directory... )

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          production-branch: production_v1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: 86a6cf74-a18c-44b0-a911-844407be218f
        timeout-minutes: 3
